### ISSUE TITLE
typo in documentation

### ISSUE THREAD

**Issue by knisterpapier** [eudes/korg-nts1-esp32#1]
hey, 

first things first: nice project! thank you for your effort, especially in documentation. 

in the readme-file, there is the following sentence under the topic compile-time selection:
I created a new file nts1_stm32.c, where I'll put the STM32-specific code. I'll do the same for the STM32 code.

i think the second "STM32" should be "ESP32", right? Nothing really important in my opinion, but maybe someone gets confused by it. 

Stay healthy!

**Comment by eudes** [comment]
Hey! Thank you for taking a look at the project and picking up the typo. You're absolutely right. Fixed now :).
